# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
variables:
  
  - group: frontend-variables # Variable Group containing 'mongoHost', 'mongoUser' and the secret 'mongoPassword'

  - name: dockerRegistryServiceConnection
    value: 'containerRegistryConnection' # make sure it matches the name you used in the service connection
  
  - name: acrEndpoint
    value: 'aksworksconreg.azurecr.io' # replace with container registry endpoint

  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: frontend
        dockerfile: '**/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'manifests'
        targetPath: 'manifests'

- stage: DeployDev
  displayName: Deploy to dev stage
  dependsOn: Build

  variables:
  - name: k8sNamespace # Kubernetes Namespace to deploy to. This variable is scoped to the DeployDev stage.
    value: 'dev2'
      
  jobs:
  - deployment: DeployDev
    displayName: Deploy to dev job
    pool:
      vmImage: ubuntu-latest

    environment: 'aksworkshop1.dev2' # name of the environment to target [env name.namespace]. This will pull in the Kubernetes service connection automatically

    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

         
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              manifests: $(System.ArtifactsDirectory)/manifests/*
              containers: '$(acrEndpoint)/frontend:$(tag)'
